import {DNASequence} from "../sequence";

let alphabet: string[] = ["A", "C", "G", "T"];
let data: string = ">Rosalind_5222\n" +
    "TACGAGAGTAGTCAGATAAAGCGGCGCTGTCCCTTTGAATGTGCCCTGATTCCATTCAGC\n" +
    "CTCATGCACTGACTGTGAGAGCGTGTGATGTAGTCGCAGTAGCAGGCGACGCCTATCGGG\n" +
    "TATTTGTTGTCGATGATGTACTCATAACTCACTTAAGATTAGGTTAGGGGTTTACCCTCA\n" +
    "CAAGCACAAATCGTCGCTCCGCTTCGTGATCGCAGAGGATCGACAGTTAACACAGAACAA\n" +
    "CAAATAAAGTGAGACGTCCTGCGCAGGTTGCTTGGATAAAGGAGGTTAAGGGTAGGGGTG\n" +
    "GCTGTCAGAGAGTTCATTCATTAGGTGATAGATCTAGGGTTGACCCCGCGATGCATAACT\n" +
    "GCTAAGCGCCAGCGACCATGCCGAGACAGGGAAAGGTATCCAGCCATGTAACTCACGTCC\n" +
    "ACTACTGTCTCAAGGAGACCAGTATGTGCAATAGACCTAGCCGAATACGGTAGGTTGATG\n" +
    "GACAGAGGCACCGAAATAGCGTGTAGCTTCGGATTACCCTTGTGTCTCAGACGCTCTCAA\n" +
    "CGGTGAGTCGATACATCAAGCCTATTACGGGTCCGGCACATCAGTTGTAGGGAGCCACGC\n" +
    "ATTGCGATTAACCACGCGCTACACCCCTGATCTATCTGGAAGTATCGTATGCACTACCTT\n" +
    "GTGTGGTATTCTGATCCTCCACAGCTATGTATTCTGGGTCCACGTATCAGAGATCACAAC\n" +
    "CTCAAAATCCATTTCCCGGTGGGCAAGATCTCGCGACCGAAATCCTACCCACGGATGAGG\n" +
    "AGCCCCGGCCGCTTACTCGTTGCGTAGACGGGCATTGGACACTAGAGCCAGGAATTTCGG\n" +
    "TACCGTTGTGCGAGCAGTTATAGTACGTGCAGTGGAAAGTTTGCTAAAAATGATCTAGAT\n" +
    "CTCATGTAGCTCCTCCTAATAGGAAAAACCATGAGGTTCCAATATTCTCTAGAGGCAGAG\n" +
    "GTGACCTTCCGTTTGCGCAGGAGGAGACGTTAACGGCCCT\n" +
    ">Rosalind_3648\n" +
    "CGACCCTCGCACTCGAACTGTAAACTGTCATTACAACTATTTTGGATCATGTGTCTTCAG\n" +
    "GCGTGAATAGTAGTCGCTTCCATCTGTATATGTGAGACCCCAGATTGGTTCTGCTTGTCA\n" +
    "GCACCCGTGAAAGATACAATCAATTTCACTAGGCTCAGAAGCCCATCGGACACGCAGTGG\n" +
    "ACTCAGTGGACGCTAATGTGTATATCTAGGGGGATGAAACATGATGCCGTTAGAATGAGT\n" +
    "TAACGGCCAGGGACGTACGCCCACTTAAAAGGACAGCGTACGGGAACCTCGTCGGGGTCG\n" +
    "ACCGACCCCCGGTACAGTACGGGGACCCCCGTATACGAATGGACGCTACACGAAGTATGA\n" +
    "CCAAGTCCCGTACTTGTGGGATCAGGTACTCAACAACCCGCGCTCGCCATGTCGACTGGG\n" +
    "GTCGTTTGCGGCCCCCGCGACGTCGAAAGTGCGCTGAGTTTCTTTCCCCGTAAGGGAGGT\n" +
    "GTGGAAGCAGTAAAAGTGCAGTCAGACTACGCCTCCGGACGCAGGAATAGCTTATTTGAT\n" +
    "TCGCATGGCAGTCGAGCGATAGACGATCCGACGTATCACAAAGAAGCCGTCACCTGTGAG\n" +
    "TAGTTGGCCCTACGTGTTGCGAGGCCATCAGACTTTTACTAGGTATCACTGTCGATGAGT\n" +
    "TGACAACCGCCAGCTAATTCTTGCACCGGGGTTCCCGCTTACGCCTTTTGGGAATAGGTT\n" +
    "CATATCCGCCCCATGTGGAGTATTTCAACCGGCCTATGTGCCCAAGAATACTCTTAGTCA\n" +
    "GCCACGGAAAAAAGATGATTAATTTCGATTAATGTAACAGCGCTTCGTTTCTCCGATAAA\n" +
    "GGGTAATCACCTCGGTCTTTCGATGCCCAACGCTTTAACATACTCGCGACAAGGCAGGTT\n" +
    "CCCAAGACGCATATGATTCACAGTGGCTGTTGAGAGCGTGATACCTGTATAGATTTGAGG\n" +
    "GATTATCAAGGGATTCAGTACCGGATATACGAAAGCCGTA\n" +
    ">Rosalind_6665\n" +
    "TTGCGTACACGCACAGCCCGTGCCGGCAGTCAGAAGTCGTACTGCCTGAAAGCGCCCTAC\n" +
    "TAATCCCCCGCACCAGCTGGCTCTATGGATGTCCTCGGTTAACTGCATGCAGATAAGATC\n" +
    "ACTCACGGCTGTTACCGCCGTCGTACGATCGAAATAACGCCAACGTCTGACCATAACAAT\n" +
    "CTATAGATTTGGTAAGACGTTCAGTGAACCGTACACTTCTCAACGCCGCTCTTCGTCATG\n" +
    "ATTCTGCGCTACAACAGTATAGAATCAGAGCGCTCGGGAGAGGATATAGTTGAGGTGGCA\n" +
    "TAACAGTAAAATGTCTAAATCGACAACAAATTACGTTCCGATAGACGCATAATTAGGTTC\n" +
    "TAGCATTCGTATGTGAGGCGGCTGCCGGAGGCTCCTGCATCAGGCGCGGATAACCCGGGC\n" +
    "ATAGAAGTGGCCATCGATAATGTGTGCGAGCTGACTCCCCACGATCGTTGGCCTCGTCCG\n" +
    "GCTCCTACAGCAATGCGCATACATTACGCACGTAGCTCTACACTGCTCTAGTCGCGTTTT\n" +
    "TGGGTGTAGTATAAGTATAATTAGAAACATAGAGGCAAACCTCTCGATAATCCTGCTTGC\n" +
    "AAGCCCCACAGACGTTCCTAGCGAACTGCGGGATTTGCCGGCTACTGGGGATAGACCGTA\n" +
    "ATAAGGTTTCGTTGAGTTTGCTCCTCAGTCCGTATGGTTGCCACATAGCGTTTCTCAATC\n" +
    "CGGAACCGGAGGGCACTTGCCACCTCAGGCCCGATCATCTGGCTTATGGCTGGCCAGGCC\n" +
    "TCTAATAGAAATGCTGAGATAGTTCTACGGTGCATATTCTGAATAGACGAGTCCAGATAC\n" +
    "GCTTGCAGAGATTCTCGTCCCTACCTCAGCCCGGAACATATGACTTCTCGGTAGCTACTG\n" +
    "ACGACACAAGTGAGGCGTGGACACTGTACGTCCACCCAACGGAATTTCAATTGGCGAGTT\n" +
    "AGCGCCTTCTTAACATTACCCGTCCCGGGGAGCAAGCGTG\n" +
    ">Rosalind_5641\n" +
    "GACCATGGGTGCGGCCAAGTACGGCGCAAGAGATTTGTGACCTCGGTACCCAACGCCTCC\n" +
    "CTCTGAGTACTCGGAACACTCATACGTCCCTTCAGGTCTTCGTTTGCCCGGCTGGGTTAT\n" +
    "TGTTCCCGAGACCAAAAAACGCATAGACGGGCCATCGCTCTGGTAGCTCGGGAGTGCAAC\n" +
    "TGCTGCAGACACTATAGGGCGTTAGGATCATCTCAAAATGCGCCGTAAAGCCATACCCAG\n" +
    "GCCGCTAGCCGCGAACAGCACCTAGAAAGACCAATAGTCTTCGATCATCGTTCCCAGCAG\n" +
    "GTACAGGCTTGCGCAGCTGTCCCCATCACGCTTACGGGTTATAGGTCTTACTTCCTCGTG\n" +
    "GAAGGACTAAGGCCCGGCTAAGGCAGATACCCCATGCCTGACTTCCCCAGGGCCGTCAGA\n" +
    "ACAACTAAGAATGTTATGGGTGGACGCAATTGGCGGCTCGAAACGATAGAGGACTTCAAG\n" +
    "ATGGAGAAATCACATTCCTACAAGTAGCGTATTTGTCAGTTAGTCCTTCGTGGTACTCTG\n" +
    "ATTCAGGGTAGAGACTGCTCACTTCGTCAAAATACGCTCAAATCACTGCCGGACATTTGT\n" +
    "GATCACCAGGGCCGGAGAGGACAGCGAAAAACCTGGGATACAACTTATTCTCCCTTAACC\n" +
    "TTACTTGTGCACCCCCTTTGTACGAAGTCCTTCTACGGGACGTATTGTGAAATTTCAGGA\n" +
    "CTCACGCTGGCTGGTTCGTGAGTCGCTCCGGCATCCCACGGCATTCCTAAACGAGTTTAG\n" +
    "GTAATCAAGGTCGCTATTTCTCTGGTCCATGATGCCTTACTGAGATGCAATTTGAGAAAG\n" +
    "TTTCGTCAACTGACCTACACTCTAGCCTTCCCGACACCACGGCCACCTGGGGCCCTCGGG\n" +
    "TAACTCTGTTTAGGCAGTCGCAGAGGTTGTCCATGGTACTTAGATGCTAATTGAGTGACC\n" +
    "TCTAACAAGGCCATGTGTAGGCCCTTCTTGGCCAGGCTAA\n" +
    ">Rosalind_7696\n" +
    "TTCTAAGCGACCAAGTTGTATAAGTCCCCTACCTGCTCGAGTCGCAAGTTAGCTTTCCAT\n" +
    "CGCATCTATATTACCTGGATTTCGGTCCTACCATGCTTTTAATCCCGAGTTAGGATTATG\n" +
    "ATTGCTAGGGAGAACCCACTATGATGCCTAGATGGTCCACATCTATATTCGGCTGGTCGG\n" +
    "TGAAGCGCCACCACTATATTAGACATGGCGCTCTAGAGTGTTGACACCACCCTTCAGAGC\n" +
    "TTATATTCTTACTCGGGTTATCGAATTAGAGGACGTCACTCGATCTCGGTTTATCACTAC\n" +
    "GGGACGCCAGTTCTGCGGGCTCGAGCCTAGAATGCCGGTGAACAATGAAGTGGGTGTGTA\n" +
    "GAGGTGCGCCGGAGGTTCTCAACATCATACAAATTGCGGTCGTGACTCGGGCATCTGCTA\n" +
    "GTGGCTAGAGCGGCGTCCGCCTCATCGGTCCCGTGTCGTGTTTTCGGCCACGAGCACGGT\n" +
    "TAGGATCGTCACGTACGCTGAGTACAATTCAGTGTACCAATTGGTTGAACAACTTCAAGT\n" +
    "CAAACCAGAAACACTGTCGCGAAATGGATACAACACCCGCACGTATGTGAGTTGTTTCCG\n" +
    "AATCGGTTCCATTGCATCTGTCAGCAACCGGGATGATAGGGAGCCATCCCTTATGATGTG\n" +
    "GGGAGGATGCCCTGCATCTACTTCTGTTCACTGCACCGAAAAATAGCAGTAGAAGATATC\n" +
    "TCGGGTCGTTGGTCTGCGCCGATGTCATGCAGGAAAACGTACTAGGCATGCGGCTCGTAT\n" +
    "ATACTTCGTGAACAGTTTTTATGTGGGATAACTAAAGTAGGGTAAGTGGTGGAGGAGCCG\n" +
    "TGGTCTGGTGGGTTTATTGGAGCGCACGCTTCACGACCGTTCGGACGAACATCCAATGGT\n" +
    "TGTAGCTAGGGGATGCCGAACGACGAGATCCATCCCCGGAGGGAGAATCGTTAAGGTCCG\n" +
    "AGGAACCGAGGCCACGTTCTGTGATACTTAGGAACTTGTC\n" +
    ">Rosalind_6360\n" +
    "AGCACTGGCTTCGGGATGAAGACGGGCTAAATGAGCTAACGCTGTTGTGAAGGCATAAAA\n" +
    "CTTCGCCTTCGTTATGGTACCGGGGACACAGCTAGCACAGGTAAGGCGGGAATCGTGGCA\n" +
    "CCAGCGGGTAAGCCTACGTTGTGGGTGCCGTTTACATGATAACTGGCATACACGCTTACG\n" +
    "CCCGGAGGAAGTCATTCGGCACTGCGAACGCAGTGAAAAGCGATTCCCTGAGCGATTGGT\n" +
    "AACCCCATCCGCGAAGTCGGGCACAGTCTCTGCCTTCGGTCAGCGCATCTAGGTCAAATC\n" +
    "AGACACTCAGACTGATTTGACATCGCTCCGTCCGAAGTGCGGCTCAGCTCATGGGGTTTC\n" +
    "AGGCCTATTTACGGAGGGGTACCTCACTGGTTGTTGTGCGCCTGGCAGTTGAGGCTTTAT\n" +
    "CCGATCGTGAAGGGTGCTTCTTCATAGTACGAAATAGAGCATGTACAGTATGCGGCGCAT\n" +
    "GCTGGGGGAGGGGTAAAGCATCTAGCAGTGCCCAATACATACCGGCAAAACCCCCTATTA\n" +
    "TTCCCCCGTTTGTGGCATCTCCGCGAGCTCGCTTTCTAGCAGCGGCCTCTTATCGTTCAT\n" +
    "GTAAGTGAGAAGCTTATCAAACTACGGTTATCGCCGATCGAAATTGGCACCCTGGTAACG\n" +
    "CAGCCCGGCTCTATCTGTGAACAAATCTTTTCACTATAGGGTTAATCGGTGGCGCGGGTT\n" +
    "TGGTAAGTTCTGCAATTCTCACACAGCTGTTGTTACTCGTAGCATCTAACGAAGAGTGTA\n" +
    "CATCAACCGGTACGGGTCGACCCGACCCTTTTCATTTTGGCCCGCTCTGTTTATAGACTA\n" +
    "CTCAACAGTTCCACGCGAAGCTGCAGTCTGTAGACAGGCGCGGATTCGTTGCGAGGACTA\n" +
    "TAGGGTTATTGAGCAGAATCCGGATGGAAGGGTTTGGAGCCCCATTTCCGTTGCTGAGAC\n" +
    "CGACTGAGGGTCAGAATGTGGCTAGTACGACGCAGATGTA\n" +
    ">Rosalind_3754\n" +
    "CCGGGGCAAAACGGAACGTAAAATTCGGTGTTCAACCGAGTCCGCGCCCTCGCTTCCCGT\n" +
    "CGACACCCTGTACCCCCCGAATCCGACCGCTAAAACATTGCTCGCGGTTAGAGGATATCC\n" +
    "GCCCAACCTAGAGGCTGTGGCTGTGCGAAGACATTTCACGACCACCCCGCATGAGGCACG\n" +
    "TTCACTCACCTGACGCAGGTTCTGTTCGTTGTTAGGTGGGACCGGCACTATCGCTATGCC\n" +
    "GTTGAACCTACAACGAACATTTGCGGTCTCTTTAAATCCGGGGTCGATGATTCGCTGTGA\n" +
    "GCGGTAGGTCCCCGGACTATCGGTGTTATAACCCGGTCACGCCTTCATGTATTTCTGTCC\n" +
    "TATTGCCCAATGCGACGTACCTTCAAACACTAGAACTTGCTATGCGGGTTAATGTATTTT\n" +
    "CACTCCTCTGCATTTGCCTCTCCACCCTTAAGCCGCCTGGTGTCGATAGATGGGTGGCTC\n" +
    "GGCAAAAGCATTAGTCTAATATCGCAACCCAGTGTCGCGCAGCGACTAATCTGTTTTCAT\n" +
    "AACACTGGTCTAGAAACAAATGTGAGTGCATACTCAAGATGCGCCGGTTACTCCCCTCGA\n" +
    "CAATACTTATCTGAGCGTTCCTTGCTCTCACTTTGCAAAGTAACAGGAGACCCTTCCGCA\n" +
    "GGGTCGTAGGCGAGCTTCCGTGATCAGAACTCGATGCCGCGGCTAAAACAAATGTTTCGC\n" +
    "ATAGAGAACTCCTTGCTAGCTGAACTCTGAGTAGAGACCAGCGGTCACCCACTCGTCAGT\n" +
    "CTGACTACGGCCTCACGCGCGTTTGAGCTTAGTTTCCAACTAACCGTGTTATAACCACCC\n" +
    "TGTTGCCAGATCGACGAAAACTATTATGTAAATCATCCAATGTAGAAAAACCTTTTCCGC\n" +
    "TGCATTTACCTCGGAACCATCCTAATTTGAGGGCAATTTTTGTCTTCCTCGTCGAGATTG\n" +
    "CAAAGGTCTTAACCCAACCGCCGGCTGCTTATAGACATCC\n" +
    ">Rosalind_9082\n" +
    "ACGTATATGTAACTAAGTGCGCCATAAATCATGGCGAACGTCCTCTGGGGCCTGCTAATA\n" +
    "TTATCTTGGGTCGACTATGTCTTTTACCATTATATATATCGGCGGAGTCCCTTGGTGTGG\n" +
    "CTGTTCAGATGCTCAGGTAGACGATTATCGGGCTTCCGAGCCGATTTGAGCATAGGATAT\n" +
    "AATTCCTGTGCTTTATTCGGAGTACCCGGAGATCGAACGAAGCTTTTTCTCCGGTCATGC\n" +
    "GTCCAGCTCTCTCCCTCACAGACGTTTTACACTCCTAAGGGGTTGTCAGGATGCAATTTG\n" +
    "TCCATTAGCCTCATCTCCCTCTAGTAGCTTCATGCAATGACGAAAAGCACACATGGGCGA\n" +
    "TATGTCTGGGTAATATTACTAATGATGGGTCGGAGTAAGTTATATGTGAAAAGCAGCTCT\n" +
    "TGCACCATGTCGGCCCGGGGTCTTGTCATTATCTGGGTGAAGTGATCGTGCGTCCACGAG\n" +
    "CATGTGACGACAATTCCCTTAACCTTTGTTTTTTATCCCGGTGGGTCCCTCTCCCTGTGC\n" +
    "ACTACAGGAAAGGTGTGCTGTTGTTTCGAGGTCATAGCAGCGCAAGCTTCACTTCTGTGG\n" +
    "TTGAAGTCCTAGTATTCCGCTGTAATCTTCTGAGGTACTATTGATCTTTTGAACGTGCAG\n" +
    "CCTGTAACTCCTGTTTCTGGGCACAACAAGTGCGTTGAGATCCAGAGACTACCAGGTTTG\n" +
    "AGAGAGTTTTTCCTGAACGTTTACTCGGGGAATAGCAGGCGCTTGCCAACTTCTTGTTTG\n" +
    "AACAGTCTGGTCAGAGTTGCGTTCGACTCGTTAGGTACGCGTTTAATGAAATATATTACC\n" +
    "ATACCCTGCCATGATCTCAAGTTAAAGAAATGTGTCATGTATTTGTTGATCTAACTGTAA\n" +
    "TATACGTAGCGGTTGCTCGAGCTTTAAACCGGCCGGGCCCAATCGAAGTGTTTCTTAACC\n" +
    "TGCCCCGTTGGGAAGGAATACGTAAAGTCTAGAGGCCGTA\n" +
    ">Rosalind_1411\n" +
    "TCAAAAAGTCACGAACGTCCAGGTTGTCCCTGAAGCTGTCTATTCTGTAATGCCTGGCCA\n" +
    "GTCATAATAATCACTAACTGTTACTGGGTATCCATCTACGCCTGACTAATTGGAACATCC\n" +
    "AAGGCTAGCTAGAAGATGCTGACGATAGATTCACACTAATCCTTTTTGGTTATTCAATGT\n" +
    "CGCGCGGGCTCAAGCTCAGTGTGTCGTTCCGGTATTCGCGTCCGTTGAGGCCAGGAAGAC\n" +
    "CACGGGACGGGCGCAACATTTGTTTAGCCCGGCCCGTGCGAGCTGCCCCGTGCTTTTCTC\n" +
    "AGAGAAGGGAAAGCCAGAGTTCATGGTCGACTGCTGGCAGTGGTGCCTCGGGAACGTCCC\n" +
    "GCGATTCGTGTGTCCTATGTATTATACATGCGCACGATGATGCGAGAGTGTGCTGGCATT\n" +
    "TCTGCGCGGCAGAACATGAATTGATAGGTCAGAATTAGCCGCGATAGAGCTCCGGCTCTA\n" +
    "TCTAACTAAAATCAAAGCCCTGAAGACCGCGTGCAGATAGGAGAGTTCGTCCAGCTCTAC\n" +
    "ATGAGCCAACAATGACGGGGAATCACGTGATGTCCTACTTCTAGGCAGCCGCACAAGAGA\n" +
    "CGTCTACCTGAAGAGTCACTCTTGAGGGATTGTCCCCCGCATTTCTTTCCGTGAGTCGCG\n" +
    "CACGGCTTAGGGAAGTCAAAAAGATCCGCGCCCCATGAGTACACTCGATACGGCCGAACG\n" +
    "TGCCCGAGAAGGCAGTCAGCTACGCTGAAGCGATCATCCGCCAGACATAAGGGCCGATGA\n" +
    "AGAAGTTACCGTCCCCACATCGCCCGTAGTCATGAGTCGCTAGCGTCCTCGCCGTCCTGG\n" +
    "GTGCTTCAGTCTCAGAACAACGTCCCCCGCAAGCTAAAGCTATGCGCTGGAGCGCGGGGA\n" +
    "ACTTGAGACTATAGTGGGTGCCATCAACCACTTCATGCAAATACCACACCGTCAAATTTA\n" +
    "ATGATTCTGATCACTTCGCGACGACCGAAACCGGCTTATA\n" +
    ">Rosalind_7571\n" +
    "GCGGGGGGGACACAGGCATCGGCAAGTGGGCATCTGGGCAAGGGGGTTGCACGTCGGTCC\n" +
    "ATTTGACGATAAGATCTCCACCCGAGAAATGATCGTGGGTGCTTCCAGCAGACGAGCCTG\n" +
    "CTTTTTGCTCCCGCCGATCCCGACCTGTTTAGAGGAGCACACAATTTGAGGCTACTCTGG\n" +
    "AGTCCTTTCAAGCAATACATTGCAGGCCCTATGGGTTAATCCACAGTATCATAGTTGAGC\n" +
    "GGACTGAGCAAATGTGCATCGGAAGACGGCATCGGAGGCCAAGTGAAGACCTCATCGGCC\n" +
    "CTTCCCGTTTTTTCAAACGGATTTAGAAAGAAAGGTCCAATATTGTGTCGGTGTCTTTAC\n" +
    "CCACTTAGTAGCTAAGTATCTCCTGTAAGGGGATTAAGGCCATAGGGCCGCTCGAATGGG\n" +
    "CCTCTGCAGCTCATCAGGGTATCCGGCGGAGGGAAATACCCTTTATCCTCCGCACCAGTA\n" +
    "CCAATCAATGATTGAACCACAAACCCGTACTCACACTTCGGAGATCGAAGAAGCTTTATA\n" +
    "CTGTACCACTCTCTTAGTTCCGATGCCACGGCTGTCTTTCACGGTACCAAGTCATATCAA\n" +
    "TTGCCTAGCACGCATTATTATTCGACAGGCGTCCCTGTAGCCCCCCTATGGTAGAGCTAT\n" +
    "TCGTTACCTAGGGCTGCGAAATCCCTATAATCGAATTTACAGCCTTGCGGGGGGAACACA\n" +
    "GTGCCGTAGGAGGTTAGTTCTGAGGTAGGTCAGACTATGTGAGCTGTATCGACCATTAGA\n" +
    "GTTGCTGATGACGGAGGTCAAATACTTCTTCTTTCGCGTTAGGTGTGCAAATTATAATAC\n" +
    "GGTGGAAAATCATGGAGTTTATCTAAACGATACGCATCGCATCCTTGCGATGAATCACAA\n" +
    "GTAAATTGTGCGAAAAAGGATCTCAGTTGGCACTTTCAATTTAACGCTAGCAGACCTCAG\n" +
    "CTCCCCAGACCCATGGGTCAGAGGTAACCCCCAATGTCGA\n";

let sequences: DNASequence[] = DNASequence.parseFastaFile(data);

let numberOfSequences: number = sequences.length;
let lengthOfSequences: number = sequences[0].sequence.length;

let occurrenceMatrix: number[][] = [];
let consensus: string = "";
for(let position: number = 0; position < lengthOfSequences; position++) {
    let localOccurrences = [0, 0, 0, 0];
    for(let sequenceIndex: number = 0; sequenceIndex < numberOfSequences; sequenceIndex++) {
        let char: string = sequences[sequenceIndex].sequence.charAt(position);
        localOccurrences[alphabet.indexOf(char)]++;
    }
    let mostCommonChar: number = localOccurrences.reduce((left, right) => left > right ? left : right);
    consensus += alphabet[localOccurrences.indexOf(mostCommonChar)];
    occurrenceMatrix.push(localOccurrences);
}

console.log(consensus);
alphabet.forEach(char => {
    let partial: string[] = [];
    for(let position: number = 0; position < lengthOfSequences; position++) {
        partial.push(String(occurrenceMatrix[position][alphabet.indexOf(char)]));
    }
    console.log(char + ": " + partial.join(" "));
});