import {DNASequence} from "../sequence";

let dnaSequence: string = DNASequence.parseFastaFile(">Rosalind_8056\n" +
    "GCGCCGTAAAGGAGAGGAGAGCGCAGTACGTCTAGACCGGCTCTCAATTTCCGGAGAGTT\n" +
    "CGTAACGTATTTGCTACCCTTTAGCGTCGGCTACAAGGCGAACGTCGCAGAACTAATCCC\n" +
    "TAGCCATGAGCGCATTATTCATTTAACGTATTCTAGCCCTCAATCGATGGCATGACCTTA\n" +
    "GACTCTGACTTATTCTCAGCCCAGGGCAAGAAATACTGGTATTTGCAAGCCGAGTTCACA\n" +
    "AGACCTGTGCAGGTATGGCAAAATAAAGGACACTCCAAGTCAGCTCGGTATGATCACTGT\n" +
    "CCAAATAGTGTGCTGCTTTTGCTGCCTGTCCAGGTCTACCAGTGCCCTCTCTCGTAATTT\n" +
    "ATCAAACCGGAGGACGTGTCAATCAAGCTGAGGCGCCCCCCTAGGTGAAAGAATTGAGGG\n" +
    "ACGCGCTAATTCGAATTATTCGGGTACCGTCCCGCCAACACAGTAATGCCACCGTTGAGT\n" +
    "TGGCGCGTTTCTGCTTAAGCAGTAGTGAACTTCCAACCCTTCTTAGGTTGTTAGTTCTCG\n" +
    "AAGTCCCACTGGATGTAAAAACGGTTAGCGTTATGACTGACGAACTCGTGCGTCGCGAGC\n" +
    "CGGTTTACCACCAACTGCCATAATCTAATTCTCTCATTTAGTACGTACTCCAGAACTTCA\n" +
    "CTTTCCCCTGGGTGTACACGATTTTCCCTTCGTTAAGGTCTACGGAACCGAGTCGGGTAC\n" +
    "CGAACTCAGAGCTTACTCAACGCCGCAGCGTTTCTGCGGGCGACGAACAGCTCTCTGGCG\n" +
    "AGACTCGCAACGTAGGATAAAGCTCAACGAAGTGTGTTTCAGAGAGCAGGCTAGACAACT\n" +
    "GCTTAGGACAACCCCTCGCGCGCG")[0].sequence;

for(let length = 4; length <= 12; length++) {
    for(let position = 0; position < dnaSequence.length - length + 1; position++) {
        let candidate = new DNASequence(dnaSequence.substr(position, length));

        if(candidate.sequence === candidate.reverseComplement().sequence) {
            console.log(position + 1 + " " + length);
        }

    }
}