import {DNASequence} from "../sequence";

let sequences = DNASequence.parseFastaFile(">Rosalind_1698\n" +
    "ATGACCATCCTTGCAACTGATCCAGTTTTAAGGGAATTCCCGTCGACTTTACTCGGCAGT\n" +
    "GTTCCGCGCATCTAATCGAGGCTACGTTCCTACCACAGTGCTGTGGTACATACGGATTCG\n" +
    "GCTGCGGAAAAGGCCATCACCCCGGAGCCGTCTATGTGCTTCGACATACTTTCGAAAAAT\n" +
    "CTGCACGGTTGCTGTTCCCCAGATGCGCCGCACCAGCTACTTATATGACCAGCGGTAACA\n" +
    "CTGTGTCATCCTGGCCCATACGCATTCGGGTGCTACCCACGCATCACCGTACAGCTCGAA\n" +
    "CGGGCGATATCAGTCTACCTCAGACCCAAGTTGCGGACTCTACCACACAGCCTTTGTCAA\n" +
    "CCCAGACACGCTACTCATGTGCCGTGCCGCATGAACACCGCAACATCCGAATAGGCTCAA\n" +
    "GTGTAGCCAAACGATGCCAATTTAGGAAGAATCATGCCACAGCACCCTTACCTAGGTAAG\n" +
    "TCCGTTTTACCTAACGGTAATGGCGGCAAATGATTAGTCCTATCGGCCATGTACAGTATA\n" +
    "ACTACAGGCTGAGGGACGCGCCTACCCCGCGCTCGGAGGGTTCCCAAAATGTTCGCGTCG\n" +
    "AATAAATTCTAGACTATACATGATATTCATGATTTCAGGATCTCACGACCAAAGTTCCAA\n" +
    "GGCACACGCTACCTACGCGTGAGTTTAACATCTGGACATGTATTCCCGATCAATGACCTT\n" +
    "GCAAGCGATCCACGTATCATTTAAGACACAGCTTTGAATTCATGGGTCGCTAGAAGTTTA\n" +
    "GGTGGGCGCGAATCGAAACTCAATAGCGCCACTATAGGTCACGAATCATCATGTTATGAT\n" +
    "AGCAAAGATCAACATATTCATCCCAAAAGTTGTGGTGTATCACCAGCCTCATACCATACA\n" +
    "CGGTACCCAGTCGGTTGAGTTCTCACTTACTCATCCCGTGA\n" +
    ">Rosalind_0048\n" +
    "GCCACTATAGGTCACGAATCATCATGTTATGATAGCAAAGATCAAC\n" +
    ">Rosalind_0175\n" +
    "GATCCAGTTTTAAGGGAATTCCCGTCGACTTTACTCGG\n" +
    ">Rosalind_7476\n" +
    "ACCCCGGAGCCGTCTATGTGCTTCGACATACTTTCGAAAAATCTGC\n" +
    ">Rosalind_8096\n" +
    "CCCTTACCTAGGTA\n" +
    ">Rosalind_3303\n" +
    "CAGCCTCATACCA\n" +
    ">Rosalind_9791\n" +
    "ATCCGAATAGGCTCAAGTGTA\n" +
    ">Rosalind_6987\n" +
    "ACATACGGATTCG\n" +
    ">Rosalind_8061\n" +
    "ACCTACGCGTGAGTTTAACATCTGGAC\n" +
    ">Rosalind_2502\n" +
    "TTGCAAGCGATCCACGTATCATTTAAGACACAGCT\n" +
    ">Rosalind_6205\n" +
    "TACCTCAGACCCAAGTTGCGGACTCTACC\n" +
    ">Rosalind_8338\n" +
    "CGGTAACACTGTGTCATCCTGGCCCATACGCATTCGGGTGCTAC\n" +
    ">Rosalind_2103\n" +
    "GATTAGTCCTATCGGCCATGTACAGTATAACTACAGGCTGA\n" +
    ">Rosalind_5344\n" +
    "TAGACTATACATGATATTCATG\n");

// @ts-ignore
let sequence = sequences.shift().sequence;

for(let intron of sequences) {
    sequence = sequence.split(intron.sequence).join("");
}

console.log(new DNASequence(sequence).RNATranscript().ProteinTranslation().sequence);